services:
  - type: web
    name: url-shortener
    runtime: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: HASHIDS_SALT
        generateValue: true
      - key: MONGO_DB_NAME
        value: url_shortener
      - key: MONGO_MAX_POOL_SIZE
        value: "10"
